### ISSUE TITLE
Fix naming of this repo

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_templates#10]
This repo name indicates some sort of company templates and 
the naming does not indicate that it is only a template for prbt_applications.
However if a company member creates a new repo the template drop_down only shows the
title, which can be misleading and mistaken for a general ROS package template for Pilz packages.

Discovered by @oibrocevic :wink:

**Comment by jschleicher** [comment]
Imho this repo could serve for templates of different types. Especially not only including a manipulator but also sensors (like camera or lidar). So this was on purpose and I don't like to change it just because prbt_default_application is the only package yet. Please add more templates and split, if the number of packages gets too large...

**Comment by agutenkunst** [comment]
So I witnessed that the following view was missleading:

![Screenshot from 2020-02-06 19-31-36](https://user-images.githubusercontent.com/29709121/73967004-62ddcd00-4917-11ea-8454-a36f25e99657.png)

one could (and did) think that this would mean starting a new pilz package (e.g. integrate a new sensor) rather than a basis for applications. On the shown view nothing states "application"

**Comment by jschleicher** [comment]
So what about `pilz_application_templates`?

**Comment by agutenkunst** [comment]
Sounds good!

I suggested the following change to GH:

![suggestion](https://user-images.githubusercontent.com/29709121/74049726-06d97e00-49d5-11ea-85f6-c2a4e8a27f50.png)

**Comment by jschleicher** [comment]
> So what about `pilz_application_templates`?

@JonathanGruner @PilzES  Do you see any problems with existing applications? Would you agree changing the name?

**Comment by JonathanGruner** [comment]
@jschleicher I dont see any problems, because pilz_templates was used as template and the application itself has an other name anyway.
But the name suggest that there will be more different templates, so I would prefer that there would be more applications if it where available. (PSEN-Scan, egp40, including cam, agv....)

Edit: 
@agutenkunst wrote:

>  This repo name indicates some sort of company templates and
> the naming does not indicate that it is only a template for prbt_applications.

Than change the name to prbt_application_templates or pilz_ros_application_templates, there are templates for other products too (Pss4000, PNOZ, Safety Eye..)

**Comment by jschleicher** [comment]
renamed and changed description.

**Comment by agutenkunst** [comment]
Thank you!
